# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-05 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainwheel',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainwheel',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mainwheel',
            name='trackid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='mainwheel',
            table='axf_wheel',
        ),
    ]
