# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20201005_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('trackid', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'axf_nav',
            },
        ),
    ]
