# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-06 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='spice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='specifies',
            new_name='specifics',
        ),
    ]
