ALL_TYPES = "0"

#ORDER
ORDER_OVERALL = "0"
ORDER_PRICE_L2H = "1"
ORDER_PRICE_H2L = "2"
ORDER_SALE_L2H = "3"
ORDER_SALE_H2L = "4"

#HTTP CODE
HTTP_USER_EXIST = 901
HTTP_EMAIL_EXIST = 902
HTTP_OK = 200

#ORDER STATUS
ORDER_STATUS_UNPAID = 1
ORDER_STATUS_UNSHIPPED = 2
ORDER_STATUS_UNDELIVERED = 3